In [1]:
import pandas as pd

In [2]:
df1 = pd.read_csv("assests/Allocated Limit for Honble MPs.csv")
df1.columns = df1.columns.str.strip().str.title()

In [3]:
df1.head()

,Sr. No.,State,Hon'Ble Members Of Parliaments,Constituency,Allocated Amount ( ₹ )
0,1,Maharashtra,AASHTIKAR PATIL NAGESH BAPURAO,HINGOLI,190289442
1,2,Jammu And Kashmir,ABDUL RASHID SHEIKH,BARAMULLAH,154773472.11
2,3,Bihar,ABHAY KUMAR SINHA,AURANGABAD_BR,147000000
3,4,West Bengal,ABHIJIT GANGOPADHYAY,TAMLUK,147000000
4,5,West Bengal,Abu Taher Khan,MURSHIDABAD,147000000

In [4]:
df2 = pd.read_csv("assests/Amount consented for Calamity.csv")
df2.columns = df2.columns.str.strip().str.title()
df2.head()

,Sr. No.,Calamity Type,Calamity Name,Hon'Ble Members Of Parliament,Date Of Consent,Consent Amount ( ₹ )
0,1,National Calamity,Flood 2025 in Punjab,Shri Gurjeet Singh Aujla,07-Dec-2025,7067400
1,2,National Calamity,Flood 2025 in Punjab,GURMEET SINGH MEET HAYER,03-Nov-2025,7500000
2,3,National Calamity,Flood 2025 in Punjab,Shri Jual Oram,10-Oct-2025,10000000
3,4,National Calamity,Andhra Pradesh rainfall and consequent floods ...,Krishna Prasad Tenneti,26-Mar-2025,1000000
4,5,National Calamity,Meppadi landslides 2024,SHAFI PARAMBIL,02-Mar-2025,2500000

In [5]:
df3 = pd.read_csv("assests/Works Recommended.csv")
df3.columns = df3.columns.str.strip().str.title()
df3['Recommended Date'] = pd.to_datetime(df3['Recommended Date'], errors='coerce')
df3.head()

C:\Users\goure\AppData\Local\Temp\ipykernel_18392\2459610875.py:1: DtypeWarning: Columns (0: Sr. No., 1: RECOMMENDED AMOUNT   ( ₹ )) have mixed types. Specify dtype option on import or set low_memory=False.
  df3 = pd.read_csv("assests/Works Recommended.csv")

,Sr. No.,Work Category,Work,State,Ida,Hon'Ble Members Of Parliament,Constituency,Work Description,Recommended Date,Recommended Amount ( ₹ ),Sanction Date
0,1,Normal/Others,WS/\t MP620/2024-2025/133166-Construction of b...,Karnataka,DHARWAD(DEPUTY COMMISSIONER DHARWAR_IDA),Pralhad Venkatesh Joshi,DHARWAD,Construction of Community Bhavan at Navalgund ...,2024-07-08,497185.0,09-Jul-2024
1,2,Trust and Society,WS/\t MP620/2025-2026/133167-Construction of r...,Karnataka,DHARWAD(DEPUTY COMMISSIONER DHARWAR_IDA),Pralhad Venkatesh Joshi,DHARWAD,Construction of College room of CBS Charitabl...,2024-07-08,500000.0,18-Sep-2025
2,3,Trust and Society,WS/\t MP620/2024-2025/133190-Construction of b...,Karnataka,DHARWAD(DEPUTY COMMISSIONER DHARWAR_IDA),Pralhad Venkatesh Joshi,DHARWAD,Construction of Community Bhavan of Veerashaiv...,2024-07-08,450000.0,23-Sep-2024
3,4,Normal/Others,WS/\t MP620/2025-2026/133191-Construction of b...,Karnataka,HAVERI(DEPUTY COMMISSIONER HAVERI_IDA),Pralhad Venkatesh Joshi,DHARWAD,Construction of Maremma Cultural bhavan at Nee...,2024-07-08,1500000.0,29-May-2025
4,5,Normal/Others,WS/\t MP620/2024-2025/133301-Construction of b...,Karnataka,DHARWAD(DEPUTY COMMISSIONER DHARWAR_IDA),Pralhad Venkatesh Joshi,DHARWAD,Construction of Cultural Bhavan at Kundagol TQ...,2024-07-09,398009.0,22-Aug-2024

In [6]:
df4 = pd.read_csv("assests/Works Sanctioned.csv")
df4.columns = df4.columns.str.strip().str.title()
df4.head()

C:\Users\goure\AppData\Local\Temp\ipykernel_18392\1768302708.py:1: DtypeWarning: Columns (0: Sr. No., 1: Sanction Amount ( ₹ )) have mixed types. Specify dtype option on import or set low_memory=False.
  df4 = pd.read_csv("assests/Works Sanctioned.csv")

,Sr. No.,Work Category,Work,State,Ida,Hon'Ble Members Of Parliament,Constituency,Work Description,Recommended Date,Sanction Date,Sanction Amount ( ₹ ),Work Status
0,1,Normal/Others,WS/\t MP620/2024-2025/133166-Construction of b...,Karnataka,DHARWAD(DEPUTY COMMISSIONER DHARWAR_IDA),Pralhad Venkatesh Joshi,DHARWAD,Construction of Community Bhavan at Navalgund ...,08-Jul-2024,09-Jul-2024,497185.0,Physical Inspection
1,2,Trust and Society,WS/\t MP620/2025-2026/133167-Construction of r...,Karnataka,DHARWAD(DEPUTY COMMISSIONER DHARWAR_IDA),Pralhad Venkatesh Joshi,DHARWAD,Construction of College room of CBS Charitabl...,08-Jul-2024,18-Sep-2025,500000.0,Sanction
2,3,Trust and Society,WS/\t MP620/2024-2025/133190-Construction of b...,Karnataka,DHARWAD(DEPUTY COMMISSIONER DHARWAR_IDA),Pralhad Venkatesh Joshi,DHARWAD,Construction of Community Bhavan of Veerashaiv...,08-Jul-2024,23-Sep-2024,450000.0,Sanction
3,4,Normal/Others,WS/\t MP620/2025-2026/133191-Construction of b...,Karnataka,HAVERI(DEPUTY COMMISSIONER HAVERI_IDA),Pralhad Venkatesh Joshi,DHARWAD,Construction of Maremma Cultural bhavan at Nee...,08-Jul-2024,29-May-2025,1500000.0,Work partially Completed
4,5,Normal/Others,WS/\t MP620/2024-2025/133301-Construction of b...,Karnataka,DHARWAD(DEPUTY COMMISSIONER DHARWAR_IDA),Pralhad Venkatesh Joshi,DHARWAD,Construction of Cultural Bhavan at Kundagol TQ...,09-Jul-2024,22-Aug-2024,398009.0,Physical Inspection

In [7]:
df5 = pd.read_csv("assests/Works Completed.csv")
df5.columns = df5.columns.str.strip().str.title()
df5.head()

,Sr. No.,Work Category,Work,State,Ida,Work Description,Hon'Ble Members Of Parliament,Constituency,Image,Completion Date,Amount Disbursed ( ₹ )
0,1,Normal/Others,WS/MP418/2024-2025/133409-Construction of road...,Bihar,ARARIA(DISTRICT PLANNING OFFICER ARARIA_IDA),PCC Road from Permeshwar Bhagat house to Ramde...,Pradeep Kumar Singh,ARARIA,NaN,05-Sep-2024,448127
1,2,Normal/Others,WS/MP18152/2024-2025/133691-Construction of ro...,Punjab,FARIDKOT(DEPUTY COMMISSIONER FARIDKOT_IDA),Construction of MID DAY Meal Shed in Govt Prim...,SARABJEET SINGH KHALSA,FARIDKOT(SC),NaN,07-Apr-2025,300000
2,3,Normal/Others,WS/MP345/2024-2025/134140-Construction of road...,Kerala,KOLLAM(DISTRICT COLLECTOR KOLLAM_IDA),Concreting of road from Janathavayanasala - P...,Shri NK Premachandran,KOLLAM,NaN,12-Aug-2024,293492
3,4,Normal/Others,WS/MP18152/2024-2025/133686-Construction of ro...,Punjab,FARIDKOT(DEPUTY COMMISSIONER FARIDKOT_IDA),Construction of MID DAY Meal Shed in Govt Prim...,SARABJEET SINGH KHALSA,FARIDKOT(SC),NaN,07-Apr-2025,300000
4,5,Normal/Others,WS/MP18152/2024-2025/133690-Construction of ro...,Punjab,FARIDKOT(DEPUTY COMMISSIONER FARIDKOT_IDA),Construction of MID DAY Meal Shed in Govt Prim...,SARABJEET SINGH KHALSA,FARIDKOT(SC),NaN,07-Apr-2025,300000

In [8]:
df6 = pd.read_csv("assests/Expenditure on Completed and On-going Works as on Date.csv")
df6.columns = df6.columns.str.strip().str.title()
df6['Work'] = df6['Work Id'] + '-' + df6['Work']
df6.head()

C:\Users\goure\AppData\Local\Temp\ipykernel_18392\3729604758.py:1: DtypeWarning: Columns (0: Sr. No., 1: Fund Disbursed Amount ( ₹ )) have mixed types. Specify dtype option on import or set low_memory=False.
  df6 = pd.read_csv("assests/Expenditure on Completed and On-going Works as on Date.csv")

,Sr. No.,State,Work,Work Id,Ida,Hon'Ble Members Of Parliament,Constituency,Expenditure Date,Vendor Name,Payment Status,Fund Disbursed Amount ( ₹ )
0,1,Uttar Pradesh,WS/MP18218/2025-2026/233777-Construction of ro...,WS/MP18218/2025-2026/233777,GHAZIABAD(DISTRICT MAGISTRAE GHAZIABAD_IDA),ATUL GARG,GHAZIABAD,21-Aug-2026,DARSH BUILDCON,Payment In-Progress,799146.0
1,2,Uttar Pradesh,WS/MP18218/2025-2026/233878-Construction of ro...,WS/MP18218/2025-2026/233878,GHAZIABAD(DISTRICT MAGISTRAE GHAZIABAD_IDA),ATUL GARG,GHAZIABAD,04-Aug-2026,DARSH BUILDCON,Payment In-Progress,832080.0
2,3,Uttar Pradesh,WS/MP18218/2025-2026/233781-Construction of ro...,WS/MP18218/2025-2026/233781,GHAZIABAD(DISTRICT MAGISTRAE GHAZIABAD_IDA),ATUL GARG,GHAZIABAD,04-Aug-2026,DARSH BUILDCON,Payment In-Progress,498309.0
3,4,Odisha,WS/MP370/2024-2025/145537-Construction of comm...,WS/MP370/2024-2025/145537,Sundaragada(DISTRICT COLLECTOR SUNDARGARH_IDA),Shri Jual Oram,SUNDARGARH (ST),31-Aug-2026,MEMBER SECY OB AND OC WWB BBSR,Payment In-Progress,2000.0
4,5,Karnataka,WS/MP18082/2025-2026/242466-Construction of ad...,WS/MP18082/2025-2026/242466,CHITRADURGA(DEPUTY COMMISSIONER CHITRADURGA_IDA),GOVIND MAKTHAPPA KARJOL,CHITRADURGA(SC),31-Aug-2026,KRIDL BHUSIRI ACCOUNT WORKS,Payment In-Progress,375000.0

In [9]:
pd.set_option('display.max_columns', None)
master_df = pd.read_csv("assests/mplads_master_analytics_ready.csv")
master_df.head(5)

C:\Users\goure\AppData\Local\Temp\ipykernel_18392\1806726466.py:2: DtypeWarning: Columns (0: Sr. No., 1: Sr. No._sanctioned) have mixed types. Specify dtype option on import or set low_memory=False.
  master_df = pd.read_csv("assests/mplads_master_analytics_ready.csv")

,Sr. No.,Work Category,Work,State,Ida,Hon'Ble Members Of Parliament,Constituency,Work Description,Recommended Date,Recommended Amount ( ₹ ),Sanction Date,Sr. No._sanctioned,Work Category_sanctioned,State_sanctioned,Ida_sanctioned,Hon'Ble Members Of Parliament_sanctioned,Constituency_sanctioned,Work Description_sanctioned,Recommended Date_sanctioned,Sanction Date_sanctioned,Sanction Amount ( ₹ ),Work Status,Completion Date,Image,total_expenditure_released,vendor_names,latest_payment_date,payment_status,Allocated Amount ( ₹ ),total_calamity_consented,net_available_fund,is_sanctioned,is_completed,has_expenditure,cost_variance,is_cost_overrun,days_to_sanction,days_to_complete,flag_unsanctioned_payment,flag_missing_completion_cert
0,1,NORMAL/OTHERS,WS/\t MP620/2024-2025/133166-CONSTRUCTION OF B...,KARNATAKA,DHARWAD(DEPUTY COMMISSIONER DHARWAR_IDA),PRALHAD VENKATESH JOSHI,DHARWAD,CONSTRUCTION OF COMMUNITY BHAVAN AT NAVALGUND ...,2024-07-08,497185.0,2024-07-09,1.0,NORMAL/OTHERS,KARNATAKA,DHARWAD(DEPUTY COMMISSIONER DHARWAR_IDA),PRALHAD VENKATESH JOSHI,DHARWAD,CONSTRUCTION OF COMMUNITY BHAVAN AT NAVALGUND ...,2024-07-08,2024-07-09,497185.0,PHYSICAL INSPECTION,2024-10-14,Images,497185.0,SHRINIVAS S MAVINAKAI CONTRACTOR,2024-10-15,PAYMENT SUCCESS,147000000.0,0.0,147000000.0,True,True,True,0.0,False,1.0,97.0,False,False
1,2,TRUST AND SOCIETY,WS/\t MP620/2025-2026/133167-CONSTRUCTION OF R...,KARNATAKA,DHARWAD(DEPUTY COMMISSIONER DHARWAR_IDA),PRALHAD VENKATESH JOSHI,DHARWAD,CONSTRUCTION OF COLLEGE ROOM OF CBS CHARITABL...,2024-07-08,500000.0,2025-09-18,2.0,TRUST AND SOCIETY,KARNATAKA,DHARWAD(DEPUTY COMMISSIONER DHARWAR_IDA),PRALHAD VENKATESH JOSHI,DHARWAD,CONSTRUCTION OF COLLEGE ROOM OF CBS CHARITABL...,2024-07-08,2025-09-18,500000.0,SANCTION,NaN,NaN,NaN,NaN,NaN,NaN,147000000.0,0.0,147000000.0,True,False,False,NaN,False,437.0,NaN,False,False
2,3,TRUST AND SOCIETY,WS/\t MP620/2024-2025/133190-CONSTRUCTION OF B...,KARNATAKA,DHARWAD(DEPUTY COMMISSIONER DHARWAR_IDA),PRALHAD VENKATESH JOSHI,DHARWAD,CONSTRUCTION OF COMMUNITY BHAVAN OF VEERASHAIV...,2024-07-08,450000.0,2024-09-23,3.0,TRUST AND SOCIETY,KARNATAKA,DHARWAD(DEPUTY COMMISSIONER DHARWAR_IDA),PRALHAD VENKATESH JOSHI,DHARWAD,CONSTRUCTION OF COMMUNITY BHAVAN OF VEERASHAIV...,2024-07-08,2024-09-23,450000.0,SANCTION,NaN,NaN,NaN,NaN,NaN,NaN,147000000.0,0.0,147000000.0,True,False,False,NaN,False,77.0,NaN,False,False
3,4,NORMAL/OTHERS,WS/\t MP620/2025-2026/133191-CONSTRUCTION OF B...,KARNATAKA,HAVERI(DEPUTY COMMISSIONER HAVERI_IDA),PRALHAD VENKATESH JOSHI,DHARWAD,CONSTRUCTION OF MAREMMA CULTURAL BHAVAN AT NEE...,2024-07-08,1500000.0,2025-05-29,4.0,NORMAL/OTHERS,KARNATAKA,HAVERI(DEPUTY COMMISSIONER HAVERI_IDA),PRALHAD VENKATESH JOSHI,DHARWAD,CONSTRUCTION OF MAREMMA CULTURAL BHAVAN AT NEE...,2024-07-08,2025-05-29,1500000.0,WORK PARTIALLY COMPLETED,NaN,NaN,850909.0,NEELAPPA G BADIGER,2026-03-05,PAYMENT SUCCESS,147000000.0,0.0,147000000.0,True,False,True,-649091.0,False,325.0,NaN,False,False
4,5,NORMAL/OTHERS,WS/\t MP620/2024-2025/133301-CONSTRUCTION OF B...,KARNATAKA,DHARWAD(DEPUTY COMMISSIONER DHARWAR_IDA),PRALHAD VENKATESH JOSHI,DHARWAD,CONSTRUCTION OF CULTURAL BHAVAN AT KUNDAGOL TQ...,2024-07-09,398009.0,2024-08-22,5.0,NORMAL/OTHERS,KARNATAKA,DHARWAD(DEPUTY COMMISSIONER DHARWAR_IDA),PRALHAD VENKATESH JOSHI,DHARWAD,CONSTRUCTION OF CULTURAL BHAVAN AT KUNDAGOL TQ...,2024-07-09,2024-08-22,398009.0,PHYSICAL INSPECTION,2025-02-03,Images,398009.0,MALLAPPA BASAPPA HARIJAN,2025-05-30,PAYMENT SUCCESS,147000000.0,0.0,147000000.0,True,True,True,0.0,False,44.0,165.0,False,False

In [10]:
master_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 107090 entries, 0 to 107089
Data columns (total 40 columns):
 #   Column                                    Non-Null Count   Dtype
---  ------                                    --------------   -----
 0   Sr. No.                                   107090 non-null  object
 1   Work Category                             107089 non-null  str
 2   Work                                      107089 non-null  str
 3   State                                     107089 non-null  str
 4   Ida                                       107090 non-null  str
 5   Hon'Ble Members Of Parliament             107089 non-null  str
 6   Constituency                              107089 non-null  str
 7   Work Description                          106974 non-null  str
 8   Recommended Date                          107089 non-null  str
 9   Recommended Amount   ( ₹ )                107090 non-null  float64
 10  Sanction Date                             78857 non-null   str
 11  Sr. No._sanctioned                        78858 non-null   object
 12  Work Category_sanctioned                  78857 non-null   str
 13  State_sanctioned                          78857 non-null   str
 14  Ida_sanctioned                            78857 non-null   str
 15  Hon'Ble Members Of Parliament_sanctioned  78857 non-null   str
 16  Constituency_sanctioned                   78857 non-null   str
 17  Work Description_sanctioned               78761 non-null   str
 18  Recommended Date_sanctioned               78857 non-null   str
 19  Sanction Date_sanctioned                  78857 non-null   str
 20  Sanction Amount ( ₹ )                     78858 non-null   float64
 21  Work Status                               78858 non-null   str
 22  Completion Date                           34319 non-null   str
 23  Image                                     25066 non-null   str
 24  total_expenditure_released                56255 non-null   float64
 25  vendor_names                              56255 non-null   str
 26  latest_payment_date                       56255 non-null   str
 27  payment_status                            56255 non-null   str
 28  Allocated Amount ( ₹ )                    107090 non-null  float64
 29  total_calamity_consented                  107090 non-null  float64
 30  net_available_fund                        107090 non-null  float64
 31  is_sanctioned                             107090 non-null  bool
 32  is_completed                              107090 non-null  bool
 33  has_expenditure                           107090 non-null  bool
 34  cost_variance                             56255 non-null   float64
 35  is_cost_overrun                           107090 non-null  bool
 36  days_to_sanction                          78857 non-null   float64
 37  days_to_complete                          34319 non-null   float64
 38  flag_unsanctioned_payment                 107090 non-null  bool
 39  flag_missing_completion_cert              107090 non-null  bool
dtypes: bool(6), float64(9), object(2), str(23)
memory usage: 28.4+ MB